{{- if .Values.beamProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-proxy
  template:
    metadata:
      labels:
        app: beam-proxy
    spec:
      containers:
        - name: beam-proxy
          image: {{ .Values.beamProxy.image | quote }}
          ports:
            - containerPort: {{ .Values.beamProxy.port }}
          {{- with .Values.beamProxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: BROKER_URL
              value: {{ .Values.beamProxy.brokerUrl | quote }}
            - name: PROXY_ID
              value: {{ .Values.beamProxy.proxyId | quote }}
            - name: {{ .Values.beamProxy.appKeyNameTask | quote }}
              valueFrom:
                secretKeyRef:
                  name: omics-beam-secret
                  key: BEAM_SECRET
            - name: {{ .Values.beamProxy.appKeyNameSocket | quote }}
              valueFrom:
                secretKeyRef:
                  name: omics-beam-secret
                  key: BEAM_SECRET
            - name: PRIVKEY_FILE
              value: "/run/secrets/proxy.pem"
            {{- with .Values.config }}
            {{- if .rootCrtPem }}
            - name: ROOTCERT_FILE
              value: "/conf/root.crt.pem"
            {{- end }}
            {{- end }}
            - name: ALL_PROXY
              value: {{ .Values.beamProxy.allProxy | quote }}
          volumeMounts:
            - name: proxy-key
              mountPath: /run/secrets
              readOnly: true
            {{- with .Values.config }}
            {{- if .rootCrtPem }}
            - name: root-cert
              mountPath: /conf/root.crt.pem
              subPath: root.crt.pem
              readOnly: true
            {{- end }}
            {{- end }}
      volumes:
        - name: proxy-key
          secret:
            secretName: beam-proxy-key
            items:
              - key: proxy.pem
                path: proxy.pem
        {{- with .Values.config }}
        {{- if .rootCrtPem }}
        - name: root-cert
          secret:
            secretName: root-cert
        {{- end }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: beam-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: beam-proxy
  ports:
    - name: http
      port: {{ .Values.beamProxy.port }}
      targetPort: {{ .Values.beamProxy.port }}
  {{- end }}