apiVersion: v1
kind: Secret
metadata:
  name: omics-beam-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  BEAM_SECRET: {{ .Values.secrets.beamSecret | quote }}
---
{{- if .Values.beamProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: beam-proxy-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_task_KEY: {{ .Values.secrets.app_task_key | quote }}
  APP_socket_KEY: {{ .Values.secrets.app_socket_key | quote }}
  proxy.pem: |-
    {{ .Values.secrets.proxyPem | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: omics-s3-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | quote }}
---
{{- if .Values.blaze.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: dwh-blaze-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.blaze.auth.username .Values.blaze.auth.password | b64enc }}
{{- end }}
