FROM lukemathwalker/cargo-chef:0.1.73-rust-1.91.0-bookworm AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /app

COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY . .
RUN cargo build --release -p itcc-omics-data-lake --bin itcc-omics-data-lake
FROM gcr.io/distroless/cc-debian12 AS runtime

COPY --from=builder /app/target/release/itcc-omics-data-lake /usr/local/bin/itcc-omics-data-lake

ENTRYPOINT ["/usr/local/bin/itcc-omics-data-lake"]
