version: "3.9"

services:
  omics-endpoint:
    build: .
    image: samply/itcc-omics-ingest
    ports:
      - "8080:8080"
    environment:
      - UPLOAD_DIR=/data/uploads
    volumes:
      - ./uploads:/data/uploads
