services:
  itcc-omics-data-lake:
    build:
      context: ..
      dockerfile: Dockerfile.dev.datalake
    image: samply/itcc-omics-data-lake
    volumes:
      - ./data:/data
    environment:
      - BEAM_ID=app1.proxy2.broker
      - BEAM_SECRET=App1Secret
      - BEAM_URL=http://proxy2:8082
      - S3_ACCESS_KEY_ID=GK8a94a82939416153a900f006
      - S3_SECRET_ACCESS_KEY=82ea80b92e838fe95b351b93a8f1d0a4bf16b187865c13702beee53cadb8b3a7
      - S3_DEFAULT_REGION=garage
      - S3_ENDPOINT_URL=http://garage:3900
      - S3_BUCKET=omics
      - RUST_LOG=debug
    networks:
      - dev_default
      - default

  garage:
    image: dxflrs/garage:v2.1.0
    container_name: garage
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ./garage-data:/var/lib/garage/data
    restart: unless-stopped
    ports:
      - "3900:3900"   # S3
      - "3901:3901"   # Admin API
      - "3902:3902"
      - "3903:3903"
    networks:
      - dev_default
      - default

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      # Admin API
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    networks:
      - dev_default
      - default

  lakekeeper-db:
    image: postgres:16
    environment:
      POSTGRES_USER: lakekeeper
      POSTGRES_PASSWORD: lakekeeper
      POSTGRES_DB: lakekeeper
    ports:
      - "5432:5432"   # optional; remove if you don't need host access
    networks:
      - dev_default
      - default

  lakekeeper:
    image: vakamo/lakekeeper:latest-main
    command: [ "serve" ]
    depends_on:
      - lakekeeper-db
    environment:
      BIND_ADDR: "0.0.0.0:8181"
      LAKEKEEPER__PG_DATABASE_URL_READ: "postgres://lakekeeper:lakekeeper@lakekeeper-db:5432/lakekeeper"
      LAKEKEEPER__PG_DATABASE_URL_WRITE: "postgres://lakekeeper:lakekeeper@lakekeeper-db:5432/lakekeeper"
      LAKEKEEPER__PG_ENCRYPTION_KEY: "dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-32bytes"
      RUST_LOG: "info"
    ports:
      - "8181:8181"
    networks:
      - dev_default
      - default

  lakekeeper-migrate:
    image: vakamo/lakekeeper:latest-main
    depends_on:
      - lakekeeper-db
    command: [ "migrate" ]
    environment:
      LAKEKEEPER__PG_DATABASE_URL_READ: "postgres://lakekeeper:lakekeeper@lakekeeper-db:5432/lakekeeper"
      LAKEKEEPER__PG_DATABASE_URL_WRITE: "postgres://lakekeeper:lakekeeper@lakekeeper-db:5432/lakekeeper"
      LAKEKEEPER__PG_ENCRYPTION_KEY: "dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-32bytes"
    networks:
      - dev_default
      - default


networks:
  dev_default:
    external: true
volumes:
  data: