
services:
  omics-endpoint:
    build:
      context: ..
      dockerfile: Dockerfile
    image: samply/itcc-omics-ingest
    ports:
      - "6080:6080"
    environment:
      - API_KEY=omics
      - RUST_LOG=debug
      - BEAM_ID=app1.proxy1.broker
      - BEAM_SECRET=App1Secret
      - BEAM_URL=http://proxy1:8083
      - DATA_LAKE_ID=app1.proxy2.broker

networks:
  dev_default:
    external: true
