apiVersion: v1
kind: Service
metadata:
  name: blaze
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: blaze
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blaze
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blaze
  template:
    metadata:
      labels:
        app: blaze
    spec:
      containers:
        - name: blaze
          image: samply/blaze:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /fhir/metadata
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
