apiVersion: v1
kind: Service
metadata:
  name: mzl-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mzl-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mzl-db
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mzl-db
  replicas: 1
  selector:
    matchLabels:
      app: mzl-db
  template:
    metadata:
      labels:
        app: mzl-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mainzelliste
            - name: POSTGRES_USER
              value: mainzelliste
            - name: POSTGRES_PASSWORD
              value: PleasePutASafePasswordHere
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
