apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: {{ .Values.namespace }}
spec:
  serviceName: garage
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: {{ .Values.garage.image | quote }}
          ports:
            - name: s3
              containerPort: {{ .Values.garage.s3Port }}
            - name: admin
              containerPort: {{ .Values.garage.adminPort }}
            {{- range .Values.garage.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
          volumeMounts:
            - name: garage-config
              mountPath: /etc/garage.toml
              subPath: garage.toml
              readOnly: true
            - name: garage-meta
              mountPath: /var/lib/garage/meta
            - name: garage-data
              mountPath: /var/lib/garage/data
      volumes:
        - name: garage-config
          configMap:
            name: garage-config
        - name: garage-meta
          persistentVolumeClaim:
            claimName: garage-meta
        - name: garage-data
          persistentVolumeClaim:
            claimName: garage-data