{{- with .Values.config }}
{{- if .rootCrtPem }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: root-cert
  namespace: {{ $.Release.Namespace }}
data:
  root.crt.pem: |-
{{ .rootCrtPem | nindent 4 }}
{{- end }}
{{- end }}