apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: omics-beam-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  BEAM_SECRET: {{ .Values.secrets.beamSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: beam-proxy-key
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  proxy.pem: |
{{ .Values.secrets.proxyPem | indent 4 }}