apiVersion: v1
kind: Secret
metadata:
  name: omics-beam-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  BEAM_SECRET: {{ .Values.secrets.beamSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: beam-proxy-key
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  proxy.pem: |
{{ .Values.secrets.proxyPem | indent 4 }}