apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: garage
  ports:
    - name: s3
      port: {{ .Values.garage.s3Port }}
      targetPort: {{ .Values.garage.s3Port }}
    - name: admin
      port: {{ .Values.garage.adminPort }}
      targetPort: {{ .Values.garage.adminPort }}
    {{- range .Values.garage.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- end }}