name: Build with rust and docker

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  rust-ingest:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: read
    with:
      image-prefix: "samply/"
      components: '[ "itcc-omics-ingest" ]'
      architectures: '[ "amd64" ]'
      cargo-fmt-check: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rust-dwh:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: read
    with:
      image-prefix: "samply/"
      components: '[ "itcc-omics-data-warehouse" ]'
      architectures: '[ "amd64" ]'
      features: '[ "", "task-polling", "socket-polling" ]'
      cargo-fmt-check: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
