name: Build with rust and docker

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  rust:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    permissions:
      contents: read
      packages: write
      pull-requests: read
      security-events: write
      statuses: read
    with:
      image-prefix: "samply/"
      components: '[ "itcc-omics-ingest", "itcc-omics-data-warehouse" ]'
      architectures: '[ "amd64"]'
      #profile: debug
      test-via-script: false
      cargo-fmt-check: true
      features: '[ "", "task-polling", "socket-polling" ]'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}